In [1]:
import pickle
with open('train_data.pkl','rb') as training:
    train = pickle.load(training)

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

plt.style.use(style='seaborn')
%matplotlib inline

In [3]:
train['text']

0               deed reason earthquak may allah forgiv us
1                    forest fire near la rong sask canada
2       resid ask shelter place notifi offic evacu she...
3             peopl receiv wildfir evacu order california
4       got sent photo rubi alaska smoke wildfir pour ...
                              ...                        
7608       two giant crane hold bridg collaps nearbi home
7609    aria ahrari thetawniest control wild fire cali...
7610                                       volcano hawaii
7611    polic investig ebik collid car littl portug eb...
7612    latest home raze northern california wildfir a...
Name: text, Length: 7613, dtype: object

In [4]:
train.head()

id keyword location                                               text  \
0   1     -99      -99          deed reason earthquak may allah forgiv us   
1   4     -99      -99               forest fire near la rong sask canada   
2   5     -99      -99  resid ask shelter place notifi offic evacu she...   
3   6     -99      -99        peopl receiv wildfir evacu order california   
4   7     -99      -99  got sent photo rubi alaska smoke wildfir pour ...   

   target                                             tokens  words_count  \
0       1  [deed, reason, earthquak, may, allah, forgiv, us]            7   
1       1       [forest, fire, near, la, rong, sask, canada]            7   
2       1  [resid, ask, shelter, place, notifi, offic, ev...           11   
3       1  [peopl, receiv, wildfir, evacu, order, califor...            6   
4       1  [got, sent, photo, rubi, alaska, smoke, wildfi...            9   

   text_len  unique_word_count  mean_word_length  
0        44                  7          5.428571  
1        37                  7          4.428571  
2        88                  9          7.090909  
3        54                  6          8.000000  
4        55                  9          5.222222

In [5]:
train.T.head()

0     \
id                                                1   
keyword                                         -99   
location                                        -99   
text      deed reason earthquak may allah forgiv us   
target                                            1   

                                          1     \
id                                           4   
keyword                                    -99   
location                                   -99   
text      forest fire near la rong sask canada   
target                                       1   

                                                       2     \
id                                                        5   
keyword                                                 -99   
location                                                -99   
text      resid ask shelter place notifi offic evacu she...   
target                                                    1   

                                                 3     \
id                                                  6   
keyword                                           -99   
location                                          -99   
text      peopl receiv wildfir evacu order california   
target                                              1   

                                                       4     \
id                                                        7   
keyword                                                 -99   
location                                                -99   
text      got sent photo rubi alaska smoke wildfir pour ...   
target                                                    1   

                                                       5     \
id                                                        8   
keyword                                                 -99   
location                                                -99   
text      rockyfir updat california hwi close direct due...   
target                                                    1   

                                                       6     \
id                                                       10   
keyword                                                 -99   
location                                                -99   
text      flood disast heavi rain caus flash flood stree...   
target                                                    1   

                               7     \
id                               13   
keyword                         -99   
location                        -99   
text      im top hill see fire wood   
target                            1   

                                                  8     \
id                                                  14   
keyword                                            -99   
location                                           -99   
text      there emerg evacu happen build across street   
target                                               1   

                                 9     ...  \
id                                 15  ...   
keyword                           -99  ...   
location                          -99  ...   
text      im afraid tornado come area  ...   
target                              1  ...   

                                                       7603  \
id                                                    10862   
keyword                                                 -99   
location                                                -99   
text      offici say quarantin place alabama home possib...   
target                                                    1   

                                                       7604  \
id                                                    10863   
keyword                                                 -99   
location                                                -99   
text      worldnew fallen powerlin glink tram updat fire...   
t

#### TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

#Unigrams
vectorizer_t = TfidfVectorizer()
X3 = vectorizer_t.fit_transform(train['text'])
X3

<7613x13544 sparse matrix of type '<class 'numpy.float64'>'
	with 66379 stored elements in Compressed Sparse Row format>

In [7]:
print(X3.todense()[0][0:].sum())

2.591222661748209


In [8]:
[x for x in X3.todense()[0][0:].tolist()[0] if x != 0]

[0.41281574450250685,
 0.4779118269464913,
 0.32800423484998237,
 0.46235750890982935,
 0.29523184489259063,
 0.3499268148374476,
 0.2649746868093606]

In [9]:
vectorizer_t.vocabulary_

{'deed': 2942,
 'reason': 9589,
 'earthquak': 3526,
 'may': 7286,
 'allah': 315,
 'forgiv': 4364,
 'us': 12513,
 'forest': 4357,
 'fire': 4208,
 'near': 7984,
 'la': 6553,
 'rong': 9996,
 'sask': 10228,
 'canada': 1754,
 'resid': 9776,
 'ask': 673,
 'shelter': 10541,
 'place': 8976,
 'notifi': 8214,
 'offic': 8346,
 'evacu': 3864,
 'order': 8510,
 'expect': 3928,
 'peopl': 8818,
 'receiv': 9605,
 'wildfir': 13028,
 'california': 1722,
 'got': 4830,
 'sent': 10423,
 'photo': 8901,
 'rubi': 10067,
 'alaska': 270,
 'smoke': 10822,
 'pour': 9124,
 'school': 10293,
 'rockyfir': 9958,
 'updat': 12479,
 'hwi': 5565,
 'close': 2212,
 'direct': 3162,
 'due': 3458,
 'lake': 6575,
 'counti': 2543,
 'cafir': 1696,
 'flood': 4282,
 'disast': 3177,
 'heavi': 5218,
 'rain': 9480,
 'caus': 1889,
 'flash': 4252,
 'street': 11260,
 'manit': 7164,
 'colorado': 2319,
 'spring': 11066,
 'area': 577,
 'im': 5673,
 'top': 12028,
 'hill': 5326,
 'see': 10371,
 'wood': 13135,
 'there': 11796,
 'emerg': 3670,
 

In [10]:
vectorizer_t.idf_

array([8.83913165, 9.24459676, 9.24459676, ..., 9.24459676, 9.24459676,
       9.24459676])

In [11]:
print(X3.todense()[0][0:].sum())

2.591222661748209


In [12]:
#Bigrams

vectorizer_t2 = TfidfVectorizer(analyzer='word', ngram_range=(1, 2))
X4 = vectorizer_t2.fit_transform(train['text'])


In [13]:
vectorizer_t2.vocabulary_

{'deed': 12812,
 'reason': 41489,
 'earthquak': 15370,
 'may': 32134,
 'allah': 1164,
 'forgiv': 19597,
 'us': 54094,
 'deed reason': 12813,
 'reason earthquak': 41496,
 'earthquak may': 15383,
 'may allah': 32136,
 'allah forgiv': 1166,
 'forgiv us': 19600,
 'forest': 19552,
 'fire': 18597,
 'near': 34739,
 'la': 28526,
 'rong': 43188,
 'sask': 44079,
 'canada': 7579,
 'forest fire': 19555,
 'fire near': 18712,
 'near la': 34762,
 'la rong': 28534,
 'rong sask': 43189,
 'sask canada': 44080,
 'resid': 42311,
 'ask': 2904,
 'shelter': 45705,
 'place': 38837,
 'notifi': 35815,
 'offic': 36293,
 'evacu': 16625,
 'order': 37040,
 'expect': 17143,
 'resid ask': 42312,
 'ask shelter': 2926,
 'shelter place': 45708,
 'place notifi': 38859,
 'notifi offic': 35816,
 'offic evacu': 36303,
 'evacu shelter': 16691,
 'place order': 38860,
 'order expect': 37052,
 'peopl': 38115,
 'receiv': 41547,
 'wildfir': 56729,
 'california': 7347,
 'peopl receiv': 38210,
 'receiv wildfir': 41551,
 'wildfir ev

In [14]:
vectorizer_t2.idf_

array([8.83913165, 9.24459676, 9.24459676, ..., 9.24459676, 9.24459676,
       9.24459676])

In [15]:
print(X4.todense()[0][0:].sum())

3.5381870776415916


In [16]:
[x for x in X4.todense()[0][0:].tolist()[0] if x != 0]

[0.2630442127859245,
 0.31849208719912,
 0.30452312435835255,
 0.31849208719912,
 0.20900272553930938,
 0.31849208719912,
 0.2946119874943592,
 0.31849208719912,
 0.18812031581473773,
 0.2946119874943592,
 0.2229716883800768,
 0.31849208719912,
 0.16884059977887275]

In [17]:
test= pd.read_csv('test.csv')
test_tfidf = vectorizer_t2.transform(test["text"])

#print(train_tfidf.todense()[0][0:].sum())

#### Logistic Regression

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

In [19]:
X = X4
y = train["target"].values

X_train_tfidf, X_test, y_train_tfidf, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
model = LogisticRegression(class_weight="balanced")
model.fit(X_train_tfidf, y_train_tfidf)

LogisticRegression(class_weight='balanced')

In [21]:
y_pred = model.predict(X_test)

f1score = f1_score(y_test, y_pred)
print(f"Tfidf Model Score: {f1score * 100} %")

Tfidf Model Score: 74.16462917685412 %


#### RidgeClassifier

In [22]:
from sklearn import feature_extraction, linear_model, model_selection, preprocessing

In [23]:
clf = linear_model.RidgeClassifier()
scores = model_selection.cross_val_score(clf, X4, train["target"], cv=3, scoring="f1")
scores

array([0.58373206, 0.52655625, 0.62302483])

In [24]:
test_vectors = vectorizer_t2.transform(test["text"])

In [25]:
clf.fit(X4, train["target"])

RidgeClassifier()

In [26]:
tfidf_prediction = clf.predict(X_test)

f1score = f1_score(y_test, tfidf_prediction)
print(f"Counts Model Score: {f1score * 100} %")

Counts Model Score: 97.24626278520849 %


In [27]:
sample_submission = pd.read_csv("sample_submission.csv")
sample_submission["target"] = clf.predict(test_vectors)

In [28]:
sample_submission.to_csv("output-2.csv", index=False)